# fly.toml app configuration file generated for lemontaxi on 2024-08-11T03:53:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lemontaxi'
primary_region = 'nrt'

[build]



[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.http_options.response.headers]
  Access-Control-Allow-Headers = '*'
  Access-Control-Allow-Methods = '*'
  Access-Control-Allow-Origin = '*'
  Access-Control-Allow-Private-Network = true


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
